### ISSUE TITLE
Custom FilamentUser class

### ISSUE THREAD

**Issue by helgur** [chiiya/filament-access-control#11]
This is really a requested feature, not a bug report (getting 404 when trying to create a request feature post). It would be great if the package user could specify what class to use in the config file so we could add our own traits (among other things) to it in order to extend the functionality.

**Comment by sagarrabadiya** [comment]
please allow which model to use as user model, for ex. I want to use existing App\Models\User model as authenticatable user, and without published config not able to use that class

**Comment by chiiya** [comment]
Implemented in [1.8.1](https://github.com/chiiya/filament-access-control/releases/tag/1.8.1)
