### ISSUE TITLE
Argument #1 ($user) must be of type FilamentUser

### ISSUE THREAD

**Issue by imrancoder** [chiiya/filament-access-control#12]
`Chiiya\FilamentAccessControl\Policies\FilamentUserPolicy::viewAny(): Argument #1 ($user) must be of type Chiiya\FilamentAccessControl\Models\FilamentUser, App\Models\User given, called in`

i have already updated filament config file `auth.pages.login` value with `\Chiiya\FilamentAccessControl\Http\Livewire\Login::class`

**Comment by chiiya** [comment]
Did you update the guard as well?

```php
'auth' => [
    'guard' => env('FILAMENT_AUTH_GUARD', 'filament'),
```

Make sure that if you're not overwriting `FILAMENT_AUTH_GUARD` with a different value.

**Comment by coder36** [comment]
I'm getting the same issue.  

<img width="967" alt="image" src="https://user-images.githubusercontent.com/561451/198913845-c9782581-cbc9-4e1f-a2f9-9933c20e5252.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/561451/198913890-47f6b671-3bf7-4da4-8e0d-f2a288fcc9b7.png">

**Comment by coder36** [comment]
Managed to get in.  I needed to update the policies to use FilamentUser:  
<img width="426" alt="image" src="https://user-images.githubusercontent.com/561451/198916154-1850cccf-de22-4ea4-9554-7bd773f326bd.png">
