### ISSUE TITLE
Missing notification on forgotten password screen

### ISSUE THREAD

**Issue by aureliusm** [chiiya/filament-access-control#13]
Hi,

on route `/admin/password/request` after you submit your email, there is no notification that the email was sent and also the email stays in the form - probably should be cleared.

Thanks for a nice package.

**Comment by chiiya** [comment]
Are you sure? There should be a notification after submitting the form.

![fac-screenshot](https://user-images.githubusercontent.com/15029301/182331528-c8335f9c-cd64-41b5-83f9-a252f3cad10c.png)

**Comment by aureliusm** [comment]
Hm, weird. Must be something in my system - sorry for the trouble. I will close this issue

**Comment by chiiya** [comment]
Actually, I can replicate this issue in the newest version of Filament. It probably has to do with their new notifications package. I'll re-open this.

**Comment by chiiya** [comment]
Should be fixed in [1.5.0](https://github.com/chiiya/filament-access-control/releases/tag/1.5.0)
