### ISSUE TITLE
Compatibility with filament-logger

### ISSUE THREAD

**Issue by cweagans** [chiiya/filament-access-control#16]
In order for the activity log exposed by [filament-logger](https://github.com/Z3d0X/filament-logger) to show users managed by this package, the `FilamentUser` model needs a method like so:

```php
    /**
     * Return a name.
     *
     * Needed for compatibility with filament-logger.
     */
    public function getNameAttribute(): string
    {
        return $this->getFilamentName();
    }
```

It's a really minor thing, but it ensures that the user who caused an event is clearly visible.

**Comment by chiiya** [comment]
Fixed in [1.6.0](https://github.com/chiiya/filament-access-control/releases/tag/1.6.0)
