### ISSUE TITLE
Filament 3.* support

### ISSUE THREAD

**Issue by brkfun** [chiiya/filament-access-control#43]
Project looks very intense and it says it requires filament ^3.0 but it is not supporting right now. You can clearly see when you install it. It tries to go to a function named getDomains which is removed in filament 3.*.
Have a nice day!

**Comment by mohandtharsha** [comment]
I have installed but after configuring this plugin I am getting below error,pxlrbt\FilamentSpotlight\Actions\RegisterUserMenu::getUrl(): Return value must be of type string, null returned 
Below is my code,
return $panel
            ->id('employer')
            ->path('employer')
            ->login()
            ->plugins([
                SpotlightPlugin::make(),
            ])

**Comment by brkfun** [comment]
still no support. Thats sad

**Comment by bashgeek** [comment]
Most updates have already been made and `dev-master` working just fine for me, just a heads up. Probably just needs some polishing and a new release.
